- examples/Makefile
- examples/README.md
- examples/src/ray.mlb
- examples/src/ray.sml
I don't know if you're interested in more examples, but if so, here's one.
Ray tracing is interesting both because of the BVH construction (which is a delightful divide-and-conquer problem), but also because the big parallel loop over all the pixels presents interesting load balancing issues.
Also, I'm really impressed with how fast MPL runs this thing.
> Add ray tracer example

- mlton/ssa/simplify-types.fun
This is the solution Matthew implemented to fix the `simplifyTypes` bug (#107) which was also present in mainline MLton (mlton/mlton#367) but had only been observed with MPL.
> simplify types fix (fixes #107)

- mlton/ssa/simplify-types.fun
The previous "simplifying" of `SimplifyTypes` was overzealous.  It ended up eliminating the aspects of the transformation that cleaned up types of cardinality 1; such types are equivalent (and many become translated) to `unit` and should be removed from types, arguments, etc.
> Fix regression in functionality of `SimplifyTypes`.

- basis-library/build/sources.mlb
- basis-library/libs/all.mlb
- basis-library/libs/basis-extra/top-level/basis-sigs.sml
- basis-library/libs/basis-extra/top-level/basis.sig
- basis-library/libs/basis-extra/top-level/basis.sml
- basis-library/libs/basis-extra/top-level/top-level.sml
- basis-library/mpl.mlb
- basis-library/mpl/file.sig
- basis-library/mpl/file.sml
- basis-library/mpl/mpl.sig
- basis-library/mpl/mpl.sml
- basis-library/primitive/prim-mpl.sml
- basis-library/primitive/primitive.mlb
- runtime/gc/virtual-memory.c
- runtime/platform.h
- runtime/platform/mmap.c
- runtime/platform/use-mmap.c
In our benchmarking, we've run into a recurring issue that it is unreasonably slow to read large files with basis IO functionality (e.g. `TextIO.inputAll`). The obvious alternative would be to use `Posix.IO` and `Posix.FileSys`, and indeed these are fast sequentially, but they also unfortunately provide no opportunity for parallelism.
There is a standard trick to work around the lack of parallelism with POSIX: just `mmap` files into memory and then read from them directly. This is fast sequentially and highly parallel. So, I implemented it in MPL.
This patch provides a structure `MPL.File` with this signature:
```
signature MPL_FILE =
sig
type t
exception Closed
val openFile: string -> t
val closeFile: t -> unit
val size: t -> int
val readChar: t -> int -> char
val readWord8: t -> int -> …
```
> Primitives for reading a file in parallel

- basis-library/build/sources.mlb
- basis-library/libs/basis-extra/top-level/basis-sigs.sml
- basis-library/mpl.mlb
- basis-library/mpl/gc.sig
- basis-library/mpl/gc.sml
- basis-library/mpl/mpl.sig
- basis-library/mpl/mpl.sml
- basis-library/primitive/prim-mlton.sml
- runtime/gc/gc_state.c
- runtime/gc/gc_state.h
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/statistics.c
- runtime/gc/statistics.h
This makes some progress on #103 and #106. 
The `MPL.GC` structures includes some statistics, including:
- number of local GCs
- time spent in local GC (wall-clock)
- time spent in promotion before local GC (wall-clock)
- bytes allocated (currently a bit funky, because includes fragmentation due to block allocation strategy)
- bytes reclaimed by local GC (also funky, due to including benefits of defragmentation)
All of these statistics come in both global and per-processor flavors. The global amount is just the sum of per-processor values; it's just for convenience.
There is also a `MPL.GC.currentHeapSize`, but this not implemented yet. I plan to implement this in the future.
> MPL.GC structure for mpl-specific gc statistics

- basis-library/mlton/thread.sig
- basis-library/mlton/thread.sml
- basis-library/primitive/prim-mlton.sml
- basis-library/schedulers/shh/Scheduler.sml
- mlton/backend/rep-type.fun
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/init-world.c
- runtime/gc/new-object.c
- runtime/gc/parallel.c
- runtime/gc/thread.c
- runtime/gc/thread.h
This implements two fixes:
- Local data allocated by scheduler workers during their idle loops is now collectible
* Scheduler threads are properly initialized at depth 1
* Each thread now has a "minimum local collection depth" which for scheduler workers is set at 1. For fork-join threads, this is set at 2, to disallow local collections at the root of the user hierarchy.
* Examples of such local data: random number generation state, idle timing counters, etc.
- Scheduler-allocated threads are now collectible
* These threads are now placed in the hierarchy and are subject to local collections.
* (By "scheduler-allocated thread" I mean the threads that are allocated in order to execute stolen tasks.)
* (Previously, these thread objects lived at depth 0, in the "global heap", which …
> Make scheduler-allocated data collectible

- runtime/gc/chunk.c
- runtime/gc/chunk.h
- runtime/gc/garbage-collection.c
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/hierarchical-heap-collection.h
- runtime/gc/init-world.c
- runtime/gc/invariant.c
- runtime/gc/local-heap.c
- runtime/gc/new-object.c
- runtime/gc/thread.c
This patch gives each stack its own chunk, similar to large arrays. Some advantages:
- Stacks can be resized in-place (if the chunk is large enough) without copying any data.
- When a stack needs to be resized larger than its current chunk, we can copy it to a new chunk and immediately reclaim the old chunk.
- During GC, stack chunks can be relocated to the to-space without any copying.
- We should no longer see the strange behavior of stacks "moving around" when they are resized. (Previously, resizing a stack allocated a new stack at the current frontier, which could be deeper than the original location of the stack.)
I did some quick tests and found that these changes are sometimes significant, e.g. in a stack-stress benchmark like `fib` I saw 20% improvement in space on 70 cores. …
> Put stacks in their own chunks (and cleanup)

- examples/Makefile
- examples/README.md
- examples/lib/CommandLineArgs.sml
- examples/lib/NewWaveIO.sml
- examples/lib/Parse.sml
- examples/lib/ReadFile.sml
- examples/lib/Signal.sml
- examples/lib/sources.mlb
- examples/src/reverb/main.sml
- examples/src/reverb/sources.mlb
Based on a design presented in this book:
> The Computer Music Tutorial (1996), page 481
> Author: Curtis Roads
Consists of 4 comb filters in parallel, fed into 2 all-pass filters in series. I also added a small amount of dynamic range compression to make everything crispy. I tuned the frequencies of the comb and all-pass filters to get something interesting: I'd say it sounds reminiscent of using a PA system in, say, a small lobby.
This patch also includes some basic support for `.wav` I/O. At the moment, the library can handle 8- and 16-bit PCM formats. If input files are multi-channel, they are immediately mixed to mono.
> New example: audio reverb effect on .wav files

- examples/Makefile
- examples/README.md
- examples/lib/Color.sml
- examples/lib/ExtraBinIO.sml
- examples/lib/GIF.sml
- examples/lib/PPM.sml
- examples/lib/Seq.sml
- examples/lib/Tokenize.sml
- examples/lib/Util.sml
- examples/lib/sources.mlb
- examples/src/nn/main.sml
- examples/src/seam-carve/SCI.sml
- examples/src/seam-carve/VerticalSeamIndexMap.sml
- examples/src/seam-carve/main.sml
- examples/src/seam-carve/sources.mlb
Seam carving is an algorithm for "content-aware resizing", allowing an image to be re-scaled while attempting to preserve the interesting features of the image. It works by removing low-energy "seams" (vertical or horizontal paths of pixels) to reduce either the width or height of the image. For more info, see https://en.wikipedia.org/wiki/Seam_carving.
This patch provides a parallel implementation. It can remove as many seams as desired, and can also generate an animation (as a .gif) of the process, showing how the image shrinks gradually as more seams are removed. It's super cool... check it out!
As part of this patch, I also implemented support for generating GIF files. This turned out to be an interesting problem of its own, because GIFs use a custom form of LZW compression. Very …
> New example: content-aware image resizing with seam-carving

- examples/Makefile
- runtime/gc.c
- runtime/gc.h
- runtime/gc/assign.c
- runtime/gc/chunk.c
- runtime/gc/chunk.h
- runtime/gc/concurrent-collection.c
- runtime/gc/concurrent-collection.h
- runtime/gc/concurrent-stack.h
- runtime/gc/deferred-promote.c
- runtime/gc/done.c
- runtime/gc/fixed-size-allocator.c
- runtime/gc/fixed-size-allocator.h
- runtime/gc/garbage-collection.c
- runtime/gc/gc_state.c
- runtime/gc/gc_state.h
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/hierarchical-heap-ebr.c
- runtime/gc/hierarchical-heap-ebr.h
- runtime/gc/hierarchical-heap.c
- runtime/gc/hierarchical-heap.h
- runtime/gc/init.c
- runtime/gc/new-object.c
In the runtime, hierarchical heaps are represented by `struct HM_HierarchicalHeap`, which we typically call "hh objects". This patch implements special memory management for hh objects, allocating them off-band instead of inside heap chunks directly.
(Some background: previously, hh objects were stored in a "start gap" in the first chunk in the heap. See #104 for more info. The advantage of doing it this way is that garbage hh objects can be implicitly collected during scavenging collection. However, there are a number of disadvantages: each heap always needs at least one chunk, and we can't reclaim any chunk that might have an hh object stored in its start gap, even if that chunk is otherwise entirely unused. This patch eliminates these problems.)
I've made a number of changes:
- The …
> Offband hierarchical heap objects, separate union-find nodes, and epoch-based reclamation

- examples/Makefile
- examples/src/coins/coins.sml
- examples/src/coins/sources.mlb
GHC's version: https://github.com/ghc/nofib/blob/f481777acf608c132db47cb8badb618ef39a0d6f/parallel/coins/coins.hs
> Add a coins benchmark from nofib

- basis-library/mlton/thread.sig
- basis-library/primitive/prim-mlton.sml
- basis-library/schedulers/shh/Scheduler.sml
When switching to a CC task in the scheduler, previously, we used the current (task) thread. The continuation embedded in this thread is therefore prevented from being scheduled for the duration of the CC. This patch fixes that.
Also, a small optimization: allocate refs rather than arrays for registering GC roots at CC. These will be a few bytes smaller.
> Don't prevent ready continuation from being scheduled when switching to CC, and other small scheduler tweaks

- runtime/gc/assign.c
- runtime/gc/concurrent-collection.c
- runtime/gc/concurrent-collection.h
- runtime/gc/concurrent-stack.c
- runtime/gc/concurrent-stack.h
- runtime/gc/hierarchical-heap.c
- runtime/gc/hierarchical-heap.h
Replaces the simple lock-based forgotten set (for snapshots) with a low-contention bag data structure. Also optimizes the communication between CC and write-barrier, to prevent unnecessary additions to the forgotten set. Specifically, CC now informs the write-barrier of its marking -> unmarking transition by "closing" the forgotten set, prevent further additions. The efficiency of this relies on the write-barrier only adding *unmarked* objects to the forgotten set, guaranteeing that the rate of additions decreases during the CC-marking phase. Eventually, after all live objects have been marked, there will be no further additions.
> Parallelize the CC stack (forgotten set)

- runtime/gc.c
- runtime/gc/cc-work-list.c
- runtime/gc/cc-work-list.h
- runtime/gc/chunk.c
- runtime/gc/concurrent-collection.c
- runtime/gc/concurrent-collection.h
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/hierarchical-heap.c
The previous CC implementation traced the memory graph via a simple recursive loop. This works fine for well-parallelized benchmarks, where it's essential to avoid deep data structures to ensure good span. But of course, it's not difficult to cook up an example to blow up the C stack during CC and lead to a crash.
This patch fixes the issue with an explicit work list, where work is enqueued onto the list, and we loop over the list to trace the memory graph. The work-list data structure is a simple list-of-chunks with LIFO ordering. We amortize additions and deletions by allocating and freeing chunks on demand.
After some initial testing, it doesn't look like this affects the performance of CC too much (both time and space), which is expected. It just removes the bad worst-case behavior.
> Switch to work list loop for CC

- runtime/gc/cc-work-list.c
- runtime/gc/cc-work-list.h
- runtime/gc/concurrent-collection.c
This implements both suggestions in #148:
* Each work list entry now contains an offset, indicating how much more of the given object needs to be traced. This allows for pushing large objects onto the work-stack in constant time and space.
* CC now performs a full DFS mark/unmark loop for each individual item pushed onto the stack. This means that the order in which objects are traced, as well as the amount of space required for CC, should be identical to 6c1af00c2f3bc970ba46b0a4f4b90e840308b550 and before.
In terms of benchmarks, `triangle-count` was previously using 30% more space due to the CC work list (as measured in discussion [here](https://github.com/MPLLang/mpl/pull/147#issuecomment-1061285273)), but now appears to be using the same amount of space as it used to. I am still …
> Better space performance for CC work list

- runtime/gc/concurrent-collection.c
- runtime/gc/foreach.c
- runtime/gc/foreach.h
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/hierarchical-heap-collection.h
A simple fix. Just changed the `GC_foreachObjptrFun` interface, and all functions that are passed as argument to things like `foreachObjptrInObject`.
These functions used to take three arguments: `(GC_state s, objptr *opp, void *env)`. Now they take four: `(GC_state s, objptr *opp, objptr op, void *env)`. The idea is that `op = *opp`, where in almost all cases, the function is called via `callIfIsObjptr` after it has checked `isObjptr(op)`. This fix ensures that `opp` is not dereferenced a second time unnecessarily.
> fix #149 by passing the read value through

- runtime/gc/entanglement-suspects.c
- runtime/gc/hierarchical-heap-collection.c
The bug was introduced in #154, as the changes in #151 weren't carried through to the entanglement suspects patch. This fixes that.
> bugfix: `copySuspect` and `clear_suspect` must adhere to `GC_foreachObjptrFun` interface

- mlton/backend/packed-representation.fun
The 0x7ffff constant should use `WordSize.objptrHeader ()`, rather than `WordSize.shiftArg`.
Bug introduced by commit cce66e8f72220d251b7c54245233e1f822d5f199 on the ec-fast branch.
> Fix `Word_andb` stmt masking type index of header

- basis-library/schedulers/shh/Scheduler.sml
- examples/Makefile
- mlton/control/control-flags.sml
- runtime/gc/cc-work-list.c
- runtime/gc/cc-work-list.h
- runtime/gc/concurrent-collection.c
This patch enables entanglement detection by default, which has nearly zero overhead (see #154) for most of our benchmarks.
> Enable entanglement detection by default (prepping for v0.3 release)

- basis-library/mpl/gc.sig
- basis-library/mpl/gc.sml
- basis-library/primitive/prim-mlton.sml
- basis-library/schedulers/shh/Scheduler.sml
- basis-library/schedulers/shh/sources.mlb
- runtime/gc/controls.h
- runtime/gc/gc_state.c
- runtime/gc/gc_state.h
- runtime/gc/hierarchical-heap.c
- runtime/gc/init.c
Adds three `@mpl ... --` runtime settings for CGC:
- `max-cc-depth`: max depth allowed for a CGC. Default is `3`. Increasing this enlarges the scope of CGC, the impact of which is not clear yet. In general, we recommend keeping CGC shallow.
- `cc-threshold-ratio`: max allowable current-size/survived ratio for CGC. Default is `2.0` (very eager). Increasing this will increase space usage, and decrease the total amount of work performed by CGC.
- `max-cc-chain-length`: max number of simultaneous CGCs allowed per heap. Default `2`. The impact of this isn't clear yet (should do some experiments)
> Some runtime controls for CGC

- runtime/gc.c
- runtime/gc.h
- runtime/gc/block-allocator.c
- runtime/gc/block-allocator.h
- runtime/gc/cc-work-list.c
- runtime/gc/chunk.c
- runtime/gc/chunk.h
- runtime/gc/concurrent-collection.c
- runtime/gc/concurrent-list.c
- runtime/gc/concurrent-list.h
- runtime/gc/concurrent-stack.c
- runtime/gc/controls.h
- runtime/gc/ebr.c
- runtime/gc/entangled-ebr.c
- runtime/gc/entanglement-suspects.c
- runtime/gc/fixed-size-allocator.c
- runtime/gc/fixed-size-allocator.h
- runtime/gc/garbage-collection.c
- runtime/gc/gc_state.h
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/hierarchical-heap.c
- runtime/gc/init.c
- runtime/gc/logger.c
- runtime/gc/logger.h
- runtime/gc/new-object.c
- runtime/gc/remembered-set.c
- runtime/gc/sampler.c
- runtime/gc/sampler.h
Tracking global block usage statistics in the block allocator, by assigning a purpose to each block and keeping track of how many blocks have been allocated/freed for that purpose.
```C
enum BlockPurpose {
BLOCK_FOR_HEAP_CHUNK,
BLOCK_FOR_REMEMBERED_SET,
BLOCK_FOR_FORGOTTEN_SET,
BLOCK_FOR_HH_ALLOCATOR,
BLOCK_FOR_UF_ALLOCATOR,
BLOCK_FOR_GC_WORKLIST,
BLOCK_FOR_UNKNOWN_PURPOSE,
...
}
```
To see block usage statistics at runtime, you can do this:
```
$ <program> @mpl procs <N> log-level block-allocator:info -- <args>
```
The default is to sample every 1 second and log the output. To control the sample rate, use the `block-usage-sample-interval` parameter:
```
$ <program> @mpl procs <N> log-level block-allocator:info block-usage-sample-interval <T> -- <args>
```
Here, we pass a time `T`, which …
> Block statistics

- basis-library/mlton/thread.sig
- basis-library/mlton/thread.sml
- basis-library/primitive/prim-mlton.sml
- basis-library/schedulers/shh/Scheduler.sml
- runtime/gc/assign.c
- runtime/gc/decheck.c
- runtime/gc/decheck.h
- runtime/gc/entanglement-suspects.c
- runtime/gc/entanglement-suspects.h
- runtime/gc/garbage-collection.c
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/hierarchical-heap.c
- runtime/gc/hierarchical-heap.h
- runtime/gc/thread.c
- runtime/gc/thread.h
Integrate with the scheduler to clear suspects in parallel. This patch subsumes #167 but I will keep the other open for now, for potential discussion.
**Performance improvements**. Big! On 72 procs, `ms-queue` is now at ~30x speedup over sequential (old: 19x), and `linden-pq` is now at ~36x speedup over sequential (old: ~30x)
**Algorithm description**. The algorithm in this patch is straightforward. Clearing suspects is a bucketed filter: some elements are eliminated, and some survive; each of the survivors is moved into one of $D$ buckets (where $D$ is the depth of the heap whose suspects are being cleared). To parallelize this, we (1) break up the input, (2) run multiple sequential filters in parallel, and then finally (3) merge the results.
**TODO: algorithmic improvements?** This …
> Clear candidates (suspects) in parallel: entanglement management perf improvement (and other fixes)

- basis-library/util/one.sml
basis-library/util/one.sml defines a structure called `One` which is used in the basis library to optimize memory usage of a few functions, including:
* Int.{fmt,toString}
* Word.{fmt,toString}
* Real.{split,toManExp}
This patch fixes a buggy race condition in the implementation of `One`. With this patch, the above functions should be safe for parallelism and concurrency.
The idea behind `One` is straightforward: a static buffer or mutable cell is allocated to be shared across calls. When a call is made, if the shared buffer is not in use, then the shared buffer can be claimed and used for the duration of that call, and then released.
The mechanism for claiming the buffer (inherited from MLton) was previously not thread-safe, because it was not atomic at the hardware level. For MLton, it …
> bugfix: update structure One to be thread-safe

- mlton/backend/ssa2-to-rssa.fun
Compiling with `-type-check true` was previously throwing an error for RSSA type checking. The problem was a mismatch between word sizes in the generated code for read barrier fast paths. The generated code used `WordSize.shiftArg` for a mask on an object header. This just needed to be changed to `WordSize.objptrHeader()`.
I cleaned up the code a little, too.
> Fix rssa type check error: word size mismatch

- basis-library/schedulers/par-pcall/Universal.sml
- basis-library/schedulers/par-pcall/sources.mlb
- mlton/atoms/atoms.fun
- mlton/atoms/atoms.sig
- mlton/atoms/exn-dec-elab.fun
- mlton/atoms/exn-dec-elab.sig
- mlton/atoms/sources.cm
- mlton/atoms/sources.mlb
- mlton/control/control-flags.sig
- mlton/control/control-flags.sml
- mlton/core-ml/core-ml.fun
- mlton/core-ml/core-ml.sig
- mlton/defunctorize/defunctorize.fun
- mlton/elaborate/elaborate-core.fun
- mlton/main/compile.fun
- mlton/xml/implement-exceptions.fun
- mlton/xml/monomorphise.fun
- mlton/xml/simplify-types.fun
- mlton/xml/type-check.fun
- mlton/xml/xml-tree.fun
- mlton/xml/xml-tree.sig
@shwestrick @colin-mcd @mikerainey 
A simple approach to avoiding the `unit ref` allocation with `structure Universal`.  Read a4eb2010b2188b6d90e830232a230e609269fc4b's commit message for the interesting details.
It will be interesting to see if this has any impact on performance.  A `unit ref` allocation ought to be just two instructions: `*frontier = header(unit ref); frontier += 8;`.  And, I guess there would be a third instruction to write the object pointer to the freshly allocated `unit ref` to the stack, in order to be live across the `pcall` and accessible in the `par` and `spwn` continuations.
If it doesn't have any impact on performance, then I wonder whether avoiding the `Universal.t` entirely and just doing the `val rightSideResult = 'b option ref` allocation in `pcallFork` is …
> Implement `structure Universal` with an applicative exception declaration

- basis-library/schedulers/par-pcall/MkScheduler.sml
- mlton/atoms/prim.fun
- mlton/atoms/prim.sig
- mlton/backend/rep-type.fun
- mlton/backend/runtime.fun
- mlton/backend/runtime.sig
- mlton/backend/ssa2-to-rssa.fun
- runtime/gc/copy-thread.c
- runtime/gc/enter_leave.c
- runtime/gc/gc_state.c
- runtime/gc/gc_state.h
- runtime/gc/handler.c
- runtime/gc/hierarchical-heap.c
- runtime/gc/init-world.c
- runtime/gc/new-object.c
- runtime/gc/thread.c
- runtime/gc/thread.h
- runtime/gen/gen-constants.c
A small change which avoids a C runtime call on the fast path of `ForkJoin.par`. The purpose of this C call, previously, was just to read and return the `spareHeartbeatTokens` field of the GCState.
We can avoid the overhead of the C runtime call by generating the appropriate code to read directly from the GCState. To do this, I implemented a new prim called `Heartbeat_tokens` which is eliminated in the `ssa2-to-rssa` pass.
I also renamed `spareHeartbeats` -> `spareHeartbeatTokens` in the runtime system for consistency.
> add prim `Heartbeat_tokens` for a faster `par` fast path

- mlton/backend/allocate-variables.fun
- mlton/backend/backend.fun
- mlton/backend/machine.fun
- mlton/backend/machine.sig
- mlton/codegen/c-codegen/c-codegen.fun
- runtime/gc/frame.h
- runtime/gc/thread.c
As suggested by @JohnReppy, rather than storing the alternate return addresses of a `PCall` on the (dynamic) call stack, one can store them in a (static) table.  In MLton, we can store the alternate return addresses in the `struct GC_frameInfo` that corresponds to the `PCALL_CONT_FRAME`.
>  Store PCall alternate return addresses in frame info

- basis-library/schedulers/par-pcall/MkScheduler.sml
We noticed previously that functions which call `ForkJoin.par` effectively take many more arguments than expected. For example, compiling this simple definition a parallel fib...
```sml
fun fib (n: Word64.word) =
if n < 0w2 then n else
let val (x, y) = ForkJoin.par (fn _ => fib (n - 0w1), fn _ => fib (n - 0w2))
in x + y
end
```
... results in this RSSA:
```
fun fib_0 (x_4373: Word64, env_8: Objptr (opt_57)) = L_2037 ()
...
L_2037 () Jump = 
x_4394: Word32 = OW32 (env_8, 12): Word32
x_4393: Objptr (opt_43) = OP (env_8, 168): Objptr (opt_43)
x_4392: Objptr (opt_50) = OP (env_8, 160): Objptr (opt_50)
x_4391: Objptr (opt_51) = OP (env_8, 152): Objptr (opt_51)
x_4390: Objptr (opt_42) = OP (env_8, 144): Objptr (opt_42)
x_4389: Objptr (opt_28) = OP (env_8, 136): Objptr (opt_28)
x_4388: Objptr …
```
> optimize `par` fast path by packaging all scheduler data into single closure

- basis-library/schedulers/par-pcall/MkScheduler.sml
- mlton/atoms/prim.fun
- mlton/atoms/prim.sig
- mlton/backend/ssa2-to-rssa.fun
- mlton/closure-convert/abstract-value.fun
- mlton/closure-convert/closure-convert.fun
- mlton/ssa/constant-propagation.fun
- mlton/ssa/deep-flatten.fun
- mlton/ssa/split-types.fun
- runtime/gc/gc_state.h
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/init.c
- runtime/gc/stack.c
- runtime/gc/thread.c
- runtime/gc/thread.h
This patch attempts a different approach for handling the eager forking optimization, approximately along these lines:
```sml
fun par(f, g) =
let
fun f'() =
( if currentSpareHeartbeatTokens() = 0 then
()
else
( Thread.atomicBegin()
; if currentSpareHeartbeatTokens() >= 1 then
tryPromoteNow()
else
()
; Thread.atomicEnd()
)
; f()
)
in
pcallFork(f', g)
end
```
The idea here is to do the `pcall` unconditionally, and then (after entry into the callee) check whether or not we can trigger a promotion eagerly. If we can, then due to the token invariants, there's only one possible frame which could be promoted (the immediate ancestor). 
To make this as fast as possible, I implemented an optimization within `GC_HH_forkThread` to promote the *youngest promotable frame*. This optimization is only …
> Avoid closure alloc on `par` fast path, fix broken token invariants, and fix subtle GC bug in `GC_HH_forkThread`

- Makefile.config
- include/c-main.h
- runtime/gc/done.c
- runtime/gc/getrusage_thread.h
- runtime/gc/handler.h
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/hierarchical-heap-ebr.h
- runtime/gc/processor.h
- runtime/gc/rusage.c
- runtime/gc/rusage.h
- runtime/gc/switch-thread.c
- runtime/gc/termination.c
- runtime/gc/thread.c
- runtime/platform/darwin.c
- runtime/platform/darwin.h
- runtime/platform/linux.h
I followed the instructions in #181.
The required `rand48_r` series functions were re-implemented as it is a GNU extension and Linux-only.
The call to `getrusage(RUSAGE_THREAD, ...)` is also replaced on this platform.
> Fix compilation on macOS

- mlton/backend/bounce-vars.fun
The `BounceVars` RSSA pass assumed that any block that was rewritten to accommodate bounced vars was `Kind.Jump`, but this is not true on the `spork` branch, because a `SpoinSync` is `Jump`-like but a distinct kind.
Closes #199
> Fix `BounceVars` handling of `SporkSpwn` and `SpoinSync` blocks

- mlton/backend/backend.fun
In the Machine IR, each block is annotated with `raises: Live.t vector option` and `returns: Live.t vector option` that indicate whether or not the function can return/raise after reaching this block and the live operands that will be returned/raised (should be `StackOffset`s).
Control down a `SporkSpwn` should never return or raise, so the translation from RSSA to Machine performs a DFS to find each block reachable from a `SporkSpwn` and tag them as `inSpwn`, so that the block is translated as `raises = NONE` and `returns = NONE`.
However, the `inSpwn` tagging was not correct for nested `Spork`s.  Leaving the DFS from one `SporkSpwn` should not reset the `inSpwn` tag to `false`; it should reset the `inSpwn` tag to the previous value.
Closes #201
> Fix `Backend` handling of nested `Spork`s

- basis-library/schedulers/hybrid/FORK_JOIN.sig
- basis-library/schedulers/hybrid/Scheduler.sml
Currently, the device identifier passed to the client code is the device number (unique identifier for the GPU). However, we need the unique identifier for the Futhark context / CUDA stream that is available. This requires passing over the index into the devices (in actuality, contexts) array.
This PR is one of 2 required for this fix. The second one aims to change how the device identifier is handled in client side code in the hybrid-bench repository.
> multi stream on GPU fix

- mlton/backend/rep-type.fun
- mlton/backend/runtime.fun
- mlton/backend/runtime.sig
- mlton/codegen/c-codegen/c-codegen.fun
- runtime/gc/enter_leave.c
- runtime/gc/foreach.c
- runtime/gc/garbage-collection.c
- runtime/gc/gc_state.c
- runtime/gc/gc_state.h
- runtime/gc/hierarchical-heap-collection.c
- runtime/gc/hierarchical-heap.c
- runtime/gc/init-world.c
- runtime/gc/invariant.c
- runtime/gc/new-object.c
- runtime/gc/stack.c
- runtime/gc/stack.h
- runtime/gc/thread.c
- runtime/gc/thread.h
- runtime/gen/gen-constants.c
This patch implements promotion stacks: an auxiliary data structure alongside every call-stack which keeps track of all of the promotable frames within that call-stack. This allows us, at each promotion, to find the oldest promotable frame in O(1) time. Previously, to find the oldest promotable frame, we had to walk the stack, costing O(#frames).
Promotion stacks are implemented using three additional values:
```c
struct GC_stack {
...
size_t promoStackReserved; // number of bytes reserved for the promotion stack
pointer promoStackBot;
pointer promoStackTop;
...
}
```
These keep track of the bottom and top of the promotion stack, where each element of the promotion stack is a pointer to a promotable frame. The bottommost element is a pointer to the oldest promotable frame; the topmost …
> Promotion stacks

- basis-library/schedulers/par-pcall/MkScheduler.sml
- basis-library/schedulers/par-pcall/sources.mlb
- basis-library/schedulers/shh/queue/DequeABP.sml
- runtime/gc.c
- runtime/gc.h
- runtime/gc/abp-deque.c
- runtime/gc/abp-deque.h
- runtime/gc/local-scope.c
- runtime/gc/switch-thread.c
- runtime/gc/thread.c
This makes it possible to use the appropriate memory order annotations, to ensure correct compilation on weakly ordered architectures such as ARM.
AFAICT, this fixes #212. On a MacBook Air M2 (2022) I'm no longer seeing these errors in my tests.
I used memory ordering annotations inspired by the ParlayLib implementation:
https://github.com/cmuparlay/parlaylib/blob/36459f42a84207330eae706c47e6fab712e6a149/include/parlay/internal/work_stealing_deque.h
One difference between our deque and the standard ABP deque is that we use the current top index of the deque to interface between the scheduler and the GC. For example, an empty deque with top=5 indicates that depths 1-4 are out of scope of LGC (because the corresponding tasks have been stolen). So, when our deque becomes empty, rather than …
> replace SML-level implementation of ABP deque with implementation in C

- include/c-chunk.h
GCC-14 no longer allows implicitly casting all pointer types to all other pointer types (https://gcc.gnu.org/gcc-14/porting_to.html#incompatible-pointer-types), the error message is shown below:
```
../mpl/lib/mlton/include/c-chunk.h: In function ‘RefP_cas’:
../mpl/lib/mlton/include/c-chunk.h:89:35: error: passing argument 1 of ‘Assignable_decheckObjptr’ from incompatible pointer type [-Wincompatible-pointer-types]
89 |   return Assignable_decheckObjptr(r, res);
|                                   ^
|                                   |
|                                   PointerAux ** {aka unsigned char **}
../mpl/lib/mlton/include/c-chunk.h:59:40: note: expected ‘Objptr’ {aka ‘unsigned char *’} but argument is of type ‘PointerAux **’ {aka ‘unsigned char **’}
59 | extern Objptr …
```
> fix gcc-14 incompatible-pointer-types error

- Dockerfile.amd64
- Dockerfile.arm64
- bin/run-docker
- docker-bake.hcl
Support for building Docker images for multiple architectures; see #209 for some context. The arm64 image performs way better and actually is quite close to directly using M1 on my laptop.
To organize the docker files better, it seems `docker buildx bake` is recommended for such use cases. LMK if you think you prefer these to be organized in a different way! For testing you can use `docker buildx bake` which builds two images, one for amd64 and one for arm64.
In addition to the above, the build process now executes `make clean` first before running `make`. This avoids output from any local `make` messing up the `make` command executed in the container.
> feat: add Docker arm64 build and revamp docker files
